// Generates the NSIS script for a published HMI package (HMI > Publish).
//
// The installer takes the Windows app straight from the template folder, file
// by file, so the ~500 MB template is never copied: only the runtime folder
// (runtime.json and the project) is staged. The template exe is installed
// under the product's name.

// Top-level template entries that are never part of a package: the editor's
// own uninstaller, and in resources/ what only an editor needs (NSIS, the
// Windows template, updater config) or what the package brings itself
export const SKIP_ROOT = [/^Uninstall .*\.exe$/i];
export const SKIP_RESOURCES = ['nsis', 'runtime', 'hmi-runtime', 'app-update.yml'];

export const COMPRESSION = {
	fast: 'SetCompressor zlib',
	small: 'SetCompressor /SOLID lzma'
};

// NSIS string contents: $ starts a variable and " ends the string
export function nsisString(s)
{
	return String(s).replace(/\$/g, '$$$$').replace(/"/g, '$\\"').replace(/[\r\n]/g, ' ');
}

// A product name as a Windows file name
export function windowsFileName(name)
{
	let s = String(name).replace(/[\x00-\x1f<>:"/\\|?*]/g, '').replace(/[. ]+$/, '').trim();

	if (/^(con|prn|aux|nul|com\d|lpt\d)$/i.test(s))
	{
		s = '_' + s;
	}

	return s.slice(0, 100);
}

// VIProductVersion needs four numbers
export function fourPartVersion(version)
{
	const parts = String(version).split('.').map(p => parseInt(p, 10));

	while (parts.length < 4)
	{
		parts.push(0);
	}

	return parts.slice(0, 4).map(n => (Number.isInteger(n) && n >= 0 && n <= 65535) ? n : 0).join('.');
}

// opts:
//   productName, version, publisher
//   exeName        installed exe file name (e.g. "Line 3.exe")
//   scope          'user' (no admin, %LOCALAPPDATA%\Programs) or 'machine'
//   desktop        desktop shortcut
//   autostart      start with Windows (Startup folder shortcut)
//   compression    'fast' or 'small'
//   outFile        installer path
//   template       {dir, exe, root: [{name, dir}], resources: [{name, dir}]}
//   runtimeDir     staged folder holding runtime.json and the project
//   join           path.join of the host platform
//   estimatedSizeKb
export function buildNsisScript(opts)
{
	const q = nsisString;
	const join = opts.join;
	const machine = opts.scope === 'machine';
	const root = machine ? 'HKLM' : 'HKCU';
	const id = windowsFileName(opts.productName) || 'HMI';
	const uninstKey = 'Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\' + id;
	const exe = opts.exeName;
	const t = opts.template;
	const lines = [];
	const add = (...l) => lines.push(...l);

	add('; Generated by HMI > Publish',
		'Unicode true',
		'ManifestDPIAware true',
		`!define PRODUCT "${q(opts.productName)}"`,
		`!define EXE "${q(exe)}"`,
		`!define UNINST_KEY "${q(uninstKey)}"`,
		'Name "${PRODUCT}"',
		`OutFile "${q(opts.outFile)}"`,
		`RequestExecutionLevel ${machine ? 'admin' : 'user'}`,
		`InstallDir "${machine ? '$PROGRAMFILES64' : '$LOCALAPPDATA\\Programs'}\\${q(id)}"`,
		`InstallDirRegKey ${root} "\${UNINST_KEY}" "InstallLocation"`,
		COMPRESSION[opts.compression] || COMPRESSION.small,
		'ShowInstDetails nevershow',
		'ShowUninstDetails nevershow',
		'',
		`VIProductVersion "${fourPartVersion(opts.version)}"`,
		'VIAddVersionKey "ProductName" "${PRODUCT}"',
		`VIAddVersionKey "ProductVersion" "${q(opts.version)}"`,
		`VIAddVersionKey "FileVersion" "${q(opts.version)}"`,
		'VIAddVersionKey "FileDescription" "${PRODUCT} Setup"',
		`VIAddVersionKey "CompanyName" "${q(opts.publisher || '')}"`,
		`VIAddVersionKey "LegalCopyright" "${q(opts.publisher || '')}"`,
		'',
		// No directory page: upgrades and the uninstaller clear folders
		// inside the install directory, which must therefore be the package's
		// own (silent installs can still pass /D=)
		'Page instfiles',
		'UninstPage uninstConfirm',
		'UninstPage instfiles',
		'',
		// A running runtime refuses to close, so it is stopped outright
		'!macro StopRuntime',
		'  nsExec::Exec \'"$SYSDIR\\taskkill.exe" /F /IM "${EXE}"\'',
		'  Pop $0',
		'  Sleep 1000',
		'!macroend',
		'',
		'Function .onInit',
		'  SetRegView 64',
		machine ? '  SetShellVarContext all' : '  SetShellVarContext current',
		'FunctionEnd',
		'',
		'Function un.onInit',
		'  SetRegView 64',
		machine ? '  SetShellVarContext all' : '  SetShellVarContext current',
		'FunctionEnd',
		'',
		'Section "Install"',
		'  !insertmacro StopRuntime',
		// Upgrades replace the app wholesale, so nothing stale survives
		'  RMDir /r "$INSTDIR\\resources"',
		'  RMDir /r "$INSTDIR\\locales"',
		'  SetOutPath "$INSTDIR"',
		`  File "/oname=\${EXE}" "${q(join(t.dir, t.exe))}"`);

	for (const e of t.root)
	{
		if (e.name === t.exe || e.name === 'resources' || SKIP_ROOT.some(r => r.test(e.name)))
		{
			continue;
		}

		add(e.dir ? `  File /r "${q(join(t.dir, e.name))}"` : `  File "${q(join(t.dir, e.name))}"`);
	}

	add('  SetOutPath "$INSTDIR\\resources"');

	for (const e of t.resources)
	{
		if (SKIP_RESOURCES.includes(e.name))
		{
			continue;
		}

		add(e.dir ? `  File /r "${q(join(t.dir, 'resources', e.name))}"` :
			`  File "${q(join(t.dir, 'resources', e.name))}"`);
	}

	add('  SetOutPath "$INSTDIR\\resources\\hmi-runtime"',
		`  File /r "${q(join(opts.runtimeDir, '*.*'))}"`,
		'  SetOutPath "$INSTDIR"',
		'',
		'  WriteUninstaller "$INSTDIR\\Uninstall.exe"',
		'  CreateShortcut "$SMPROGRAMS\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"');

	if (opts.desktop)
	{
		add('  CreateShortcut "$DESKTOP\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"');
	}
	else
	{
		add('  Delete "$DESKTOP\\${PRODUCT}.lnk"');
	}

	if (opts.autostart)
	{
		add('  CreateShortcut "$SMSTARTUP\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"');
	}
	else
	{
		add('  Delete "$SMSTARTUP\\${PRODUCT}.lnk"');
	}

	add(`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayName" "\${PRODUCT}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayVersion" "${q(opts.version)}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "Publisher" "${q(opts.publisher || '')}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayIcon" "$INSTDIR\\\${EXE}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "InstallLocation" "$INSTDIR"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "QuietUninstallString" '"$INSTDIR\\Uninstall.exe" /S'`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "NoModify" 1`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "NoRepair" 1`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "EstimatedSize" ${Math.max(0, Math.round(opts.estimatedSizeKb || 0))}`,
		'SectionEnd',
		'',
		'Function .onInstSuccess',
		'  IfSilent done',
		'  MessageBox MB_YESNO|MB_ICONQUESTION "Start ${PRODUCT} now?" IDNO done',
		'  Exec \'"$INSTDIR\\${EXE}"\'',
		'  done:',
		'FunctionEnd',
		'',
		'Section "Uninstall"',
		'  !insertmacro StopRuntime',
		'  Delete "$SMPROGRAMS\\${PRODUCT}.lnk"',
		'  Delete "$DESKTOP\\${PRODUCT}.lnk"',
		'  Delete "$SMSTARTUP\\${PRODUCT}.lnk"',
		'  RMDir /r "$INSTDIR\\resources"',
		'  RMDir /r "$INSTDIR\\locales"',
		'  Delete "$INSTDIR\\*.*"',
		'  RMDir "$INSTDIR"',
		`  DeleteRegKey ${root} "\${UNINST_KEY}"`,
		'SectionEnd',
		'');

	return lines.join('\n');
}

// Progress from makensis -V4 output, one line per file added:
//   File: "name" N bytes                          (solid)
//   File: "name" [compress] N bytes               (stored as is)
//   File: "name"->"dest" [compress] C/N bytes     (compressed to C)
// Returns the file's size N, or 0.
export function parseFileBytes(line)
{
	const m = /^File: ".*?"(?:->".*?")? (?:\[compress\] )?(?:\d+\/)?(\d+) bytes/.exec(line);

	return m ? parseInt(m[1], 10) : 0;
}
